# Generated by Django 5.1.2 on 2024-10-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Numero', models.CharField(max_length=100)),
                ('Date_vm', models.DateField(blank=True, null=True)),
                ('Date_fts', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
