# Generated by Django 5.1.2 on 2024-10-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Date_fts',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Date_vm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
